### ISSUE TITLE
Use recommended options for "jsx-a11y/no-noninteractive-element-to-interactive-role"

### ISSUE THREAD

**Issue by axelboc** [ljosberinn/eslint-config-galex#148]
At the moment, the rule is set to `error` without any options. The idea is to allow things like `<ul role="menu" />`, which is valid ARIA markup, as explained here: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-noninteractive-element-to-interactive-role.md#rule-details .

**Comment by ljosberinn** [comment]
Thanks, must've overseen that, fixing!
