### ISSUE TITLE
CRA depends on eslint-plugin-testing-library@^3.9.2

### ISSUE THREAD

**Issue by axelboc** [ljosberinn/eslint-config-galex#151]
The latest release of `eslint-config-galex` bumps `eslint-plugin-testing-library` to version `3.10.0`, which is incompatible with `react-scripts` v4.0. As a result, I'm getting the following error:

> Definition for rule 'testing-library/no-await-sync-events' was not found  testing-library/no-await-sync-events

I'm using NPM so I can't yet override module resolutions.

**Comment by ljosberinn** [comment]
Would this resolve itself after manually installing `eslint-plugin-testing-library` too?

**Comment by axelboc** [comment]
It does but I'm not sure it's a good solution, since this will likely occur with other plugins as well. CRA will always take a bit of time to bump its dependencies. 😞 

A solution could be to keep the base configuration compatible with CRA and to provide an "evergreen" config extension. The rules from the extension could then be moved into the base config as soon as CRA supports them.

**Comment by ljosberinn** [comment]
I'm afraid that's the world we live in with CRA. Hence the pre-4.0 solution of explicitly installing `@typescript-eslint` too.

Manually checking which rule is included in CRAs version involves some overhead; right now it's small. The larger issue to me would be having to sync this repos implementation with the upgrade path of CRA. That doesn't feel right as a gut reaction. I'll think about it.

**Comment by axelboc** [comment]
Alternatively we could try to convince CRA to use carets in their ESLint plugin versions,. but it would be challenging... https://github.com/facebook/create-react-app/issues/7611 😅

**Comment by axelboc** [comment]
Just had the same issue with `@typescript-eslint/no-confusing-void-expression`. Disabling the rules in the TypeScript overrides seems like an acceptable solution. :+1:

**Comment by ljosberinn** [comment]
hmmm... adding `@typescript-eslint/eslint-plugin` within `resolutions` maybe help 🤔 gotta explore that as easy trick around
