### ISSUE TITLE
@typescript-eslint/non-nullable-type-assertion-style conflicts with other rule

### ISSUE THREAD

**Issue by axelboc** [ljosberinn/eslint-config-galex#235]
The code below in my codebase triggers a warning suggesting I use `!` instead of `as Entity`. The warning comes from this rule: [@typescript-eslint/non-nullable-type-assertion-style](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/non-nullable-type-assertion-style.md).

```ts
if (childCache.has(path)) {
  return childCache.get(path) as Entity;
}
```

However, when I make the change, I get an error because of rule [@typescript-eslint/no-non-null-assertion](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-non-null-assertion.md). I personally prefer the casting to be explicit -- `!` can easily be missed -- so I would recommend disabling `@typescript-eslint/non-nullable-type-assertion-style`.

**Comment by ljosberinn** [comment]
Thank you - I agree, have also had a few issues with said rule and will look to disable it soon :)

**Comment by axelboc** [comment]
Awesome, thanks a lot! And for the other changes as well 😉
