### ISSUE TITLE
[react] @babel/eslint-parser expects presence of babel.config.js

### ISSUE THREAD

**Issue by ljosberinn** [ljosberinn/eslint-config-galex#293]
solve by:

if project is CRA:
- adding babel presets of CRA

if project is Next:
- `next/babel` if next is present

otherwise:
- try to detect babel.config.js / .babelrc / babel.config.json
- if missing, warn

**Comment by ljosberinn** [comment]
Can confirm this error so far:
> Parsing error: This experimental syntax requires enabling one of the following parser plugin(s): 'jsx, flow, typescript' (6:4)

however, using `createConfig` crashes for me with `Error: Failed to load parser '@babel/eslint-parser' declared in '.eslintrc.js#overrides[0]': Cannot find module '@babel/eslint-parser'`.

Working on it.

**Comment by ljosberinn** [comment]
Found a solution, publishing fix soon!

**Comment by axelboc** [comment]
It works beautifully, thank you so much!

**Comment by axelboc** [comment]
Arf, I've updated the config in another CRA project, this time _with_ TypeScript, and now I get the env var error on `.eslintrc.js` 😂 

```
Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: undefined.
```

Seems like the file is now being processed with the Babel parser instead of the TypeScript parser, or something of the sort.

**Comment by ljosberinn** [comment]
Afraid I can't confirm this one, got a repro? I just ran:

```sh
npx create-react-app@latest demo-eslint --template typescript
cd demo-eslint
yarn add -D eslint eslint-config-galex
touch .eslintrc.js
```

```js
// .eslintrc.js
const { createConfig } = require('eslint-config-galex/src/createConfig');

module.exports = createConfig();
```

then this works just fine, even without installing the mentioned dependencies in the docs:

![image](https://user-images.githubusercontent.com/29307652/131333416-682046a5-7406-4f2a-a3e6-188f5c535d29.png)

**Comment by axelboc** [comment]
The error comes from linting `.eslintrc.js` itself, which your command skips (`eslint src`), but it also concerns any other `JS` file.

**Comment by ljosberinn** [comment]
Ah, that explains it!

**Comment by axelboc** [comment]
🚀 🚀 🚀
