### ISSUE TITLE
`eslint-plugin-regexp`

### ISSUE THREAD

**Issue by axelboc** [ljosberinn/eslint-config-galex#311]
Just came across this plugin: https://github.com/ota-meshi/eslint-plugin-regexp -- might be a good one to add to the list!

**Comment by ljosberinn** [comment]
Thanks, came across it last weekend too and it's on the list :) bit cautios at this point however since its not v1 yet.

**Comment by ljosberinn** [comment]
sadly no update yet almost a year later so ill close. feel free to reopen should they upgrade
