### ISSUE TITLE
Add `/` marker to spaced-comment config

### ISSUE THREAD

**Issue by axelboc** [ljosberinn/eslint-config-galex#315]
In CRA, there's a file called `react-app-env.d.ts` with a triple-slash comment:

![image](https://user-images.githubusercontent.com/2936402/115361815-3b43ef00-a1c1-11eb-9843-56f871f6a463.png)

I believe `spaced-comment` can be configured as such to remove the warning:

```json
"spaced-comment": ["error", "always", { "markers": ["/"] }]
```

**Comment by ljosberinn** [comment]
ah interesting, thanks! you can alternatively use this syntax:

```ts
import 'react-scripts/types/index'
```
(not sure if the path is correct, this is its translated for [next.js](https://github.com/ljosberinn/personal-react-boilerplate/blob/master/next-env.d.ts) which also used that syntax

I'll test and adjust :)

**Comment by axelboc** [comment]
oh good to know, thanks!
