### ISSUE TITLE
Parsing error: Unexpected token <

### ISSUE THREAD

**Issue by chrish-d** [ljosberinn/eslint-config-galex#494]
I'm using these eslint rules in a monorepo across two packages (_studio_ and _web_). On the _studio_ package it works absolutely fine, but on the _web_ package it doesn't seem to be working at all and I get the above error.

The _web_ package is using NextJS so perhaps I'm missing something. I've tried all manor of things to get it working like adding parsing options, babel configs, etc, but nothing seems to work.

I was wondering if I was missing something? I made the repo public below...

https://github.com/Modular-Everything/UEFA

**Edit:** I'm just noticing that the linting _is_ working, but only in certain files. Editing [sanity.js](https://github.com/Modular-Everything/UEFA/blob/99e59d262da7eb17eb8158623a677863bb925d34/packages/web/lib/sanity.js) I get the linting errors, but the error mentioned in the title comes from editing [index.js](https://github.com/Modular-Everything/UEFA/blob/99e59d262da7eb17eb8158623a677863bb925d34/packages/web/pages/index.js)

**Comment by ljosberinn** [comment]
hi, thank you for filing this - it appears youre missing something trivial:

in `.vscode/settings.json`, you're declaring `workingDirectories` as `./studio` and `./web`, however they actually are `./packages/studio` and `./packages/web` respectively.

With that sole change (notice git tab), it should work:

![image](https://user-images.githubusercontent.com/29307652/142732340-64182177-fee1-4956-a0a1-5d16af28dcf8.png)

Please let me know if this solves it for you :)

**Comment by chrish-d** [comment]
You're absolutely right, that was the problem. I think I set these a bit earlier on in the project and to be honest completely forgot about them.

Thanks for helping me troubleshoot even though it wasn't technically related to your package — saved me a big load of headache 😁
