### ISSUE TITLE
TS error with `createConfig`

### ISSUE THREAD

**Issue by axelboc** [ljosberinn/eslint-config-galex#657]
Hey, I'm getting a TS error with the latest v4 when using `createConfig` with just the `rules` and `overrides` options like in the README. It seems that TS thinks that `cwd` and a bunch of other options are mandatory.

I think the default values for all those options should be duplicated in the function signature of `createConfig` - e.g. `cwd = process.cwd()`, or set to `undefined`.

**Comment by ljosberinn** [comment]
should be fixed with 89b64983a93ff99794bb22302f547737f1c9cbab

**Comment by ljosberinn** [comment]
thanks, should be fixed in latest version; I've tested with [your config here](https://github.com/silx-kit/h5web/blob/main/eslint.shared.js) to confirm its working :)
