### ISSUE TITLE
initial v5 plans

### ISSUE THREAD

**Issue by ljosberinn** [ljosberinn/eslint-config-galex#666]
- [ ] fix #665
- [ ] [implement FlatConfig ](https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new) 
  - can technically be implemented prior, as its already available via `configType: 'flat'`. but eventually once this is the eslint default (v9?) its going to be a breaking change for this aswell
- [ ] #622
  - [ ] which also includes updating the readme to v5
- [ ] #573
- [x] #593
- [ ] #551
- ~~[ ] #311~~
- [ ] allow standalone generation to have the same customizability as the so-far canonical way 
  - [ ] make it the default?

**Comment by TKDev7** [comment]
Maybe add json, vitest and playwright eslint plugins too?

**Comment by ljosberinn** [comment]
- [ ] evaluate [`eslint-plugin-json`](https://www.npmjs.com/package/eslint-plugin-json)
- [ ] evaluate [`eslint-plugin-vitest`](https://www.npmjs.com/package/eslint-plugin-vitest)
- [ ] evaluate [`eslint-plugin-playwright`](https://www.npmjs.com/package/eslint-plugin-playwright)

**Comment by ljosberinn** [comment]
superceded by https://github.com/ljosberinn/eslint-config-galex/issues/780
